In [1]:
#Name: Rishabh Kedia

In [89]:
import numpy as np

In [104]:
#Create matrix A with size (3,5) containing random numbers
a = np.random.random(15).reshape(3,5)
print('A: %s' %a)

A: [[ 0.1989134   0.26943841  0.45409686  0.8931826   0.41490198]
 [ 0.1561664   0.09971606  0.05990208  0.57347287  0.35389622]
 [ 0.63310774  0.74166118  0.26535256  0.54182125  0.52325784]]


In [105]:
#Find the size and length of matrix A
print('A size: %s' %a.size)
print('A length: %s' %a[0].size)

A size: 15
A length: 5


In [106]:
#Resize (crop/slice) matrix A to size (3,4)
a = a.flatten()[0:12].reshape(3,4)
print('A: %s' %a)

A: [[ 0.1989134   0.26943841  0.45409686  0.8931826 ]
 [ 0.41490198  0.1561664   0.09971606  0.05990208]
 [ 0.57347287  0.35389622  0.63310774  0.74166118]]


In [107]:
#Find the transpose of matrix A and assign it to B
b = a.T
print('B: %s' %b)

B: [[ 0.1989134   0.41490198  0.57347287]
 [ 0.26943841  0.1561664   0.35389622]
 [ 0.45409686  0.09971606  0.63310774]
 [ 0.8931826   0.05990208  0.74166118]]


In [108]:
#Find the minimum value in column 1 of matrix B
print('Minimum value in column 1 of matrix B: %s' %np.min(b[:,0])) #means each row in the first column or 0th index column

Minimum value in column 1 of matrix B: 0.198913398433


In [109]:
#Find the minimum and maximum values for the entire matrix A
print('Max in A: %s' %np.max(a))
print('Min in A: %s' %np.min(a))

Max in A: 0.893182598683
Min in A: 0.0599020838802


In [110]:
#Create vector X (an array) with 4 random numbers
x = np.random.random((4))
print('X: %s' %x)

X: [ 0.68066737  0.03955552  0.83933961  0.40600009]


In [111]:
#Create a function and pass vector X and matrix A in it
#In the new function multiply vector X with matrix A and assign the result to D
def multiply(a, x):
    return a*x

In [112]:
d = multiply(a, x)
print('D: %s' %d)

D: [[ 0.13539386  0.01065778  0.38114148  0.36263222]
 [ 0.28241024  0.00617724  0.08369563  0.02432025]
 [ 0.39034427  0.01399855  0.5313924   0.30111451]]


In [113]:
#Create a complex number Z with absolute and real parts != 0
z = 2 + 3j

In [114]:
#Show its real and imaginary parts as well as it’s absolute value
print('Z Real: %s' %np.real(z))
print('Z Imaginary: %s' %np.imag(z))
print('Z Absolute: %s' %np.abs(z))

Z Real: 2.0
Z Imaginary: 3.0
Z Absolute: 3.60555127546


In [115]:
#Multiply result D with the absolute value of Z and record it to C
c = d * np.abs(z)
print('C: %s' %c)

C: [[ 0.48816951  0.03842716  1.37422514  1.30748906]
 [ 1.01824461  0.02227236  0.3017689   0.08768791]
 [ 1.40740629  0.05047248  1.91596255  1.0856838 ]]


In [116]:
#Convert matrix B from a matrix to a string and overwrite B
print('B: %s' %np.array_str(b.flatten()))

B: [ 0.1989134   0.41490198  0.57347287  0.26943841  0.1561664   0.35389622
  0.45409686  0.09971606  0.63310774  0.8931826   0.05990208  0.74166118]


In [117]:
#Display a text on the screen: ‘Your Name is done with HW2‘
print('Rishabh Kedia is done with HW2')

Rishabh Kedia is done with HW2
